function foo() {
	console.log(x);
}


try{
	foo();
}catch(err){
	console.error(err.message);

}

